export const countryCodes = [
  { code: "91", country: "India" },
  { code: "1", country: "United States" },
  { code: "44", country: "United Kingdom" },
  { code: "86", country: "China" },
  { code: "81", country: "Japan" },
  { code: "49", country: "Germany" },
  { code: "33", country: "France" },
  { code: "39", country: "Italy" },
  { code: "7", country: "Russia" },
  { code: "55", country: "Brazil" },
  { code: "52", country: "Mexico" },
  { code: "61", country: "Australia" },
  { code: "65", country: "Singapore" },
  { code: "971", country: "UAE" },
  { code: "966", country: "Saudi Arabia" },
  { code: "20", country: "Egypt" },
  { code: "234", country: "Nigeria" },
  { code: "27", country: "South Africa" },
  { code: "82", country: "South Korea" },
  { code: "92", country: "Pakistan" },
].sort((a, b) => a.country.localeCompare(b.country));
