"""fix_campaign_id_type

Revision ID: 1a7d2a67e9a9
Revises: 2ca830e14bac
Create Date: 2025-01-18 07:41:35.758632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7d2a67e9a9'
down_revision: Union[str, None] = '2ca830e14bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
