"""empty message

Revision ID: df0010497536
Revises: 458a1c2d5321
Create Date: 2025-01-18 22:26:57.629875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df0010497536'
down_revision: Union[str, None] = '458a1c2d5321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('template_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'template_data')
    # ### end Alembic commands ###
